FROM hipache:0.3.1
MAINTAINER n-oshrio@j-hack.co.jp

RUN npm install -g eventemitter3@0.1.6 hipache@0.3.1 --production

ENV SERVER_ACCESSLOG /var/log/hipache-access.log
ENV SERVER_WORKERS 10
ENV SERVER_MAXSOCKETS 100
ENV SERVER_DEADBACKENDTTL 30
ENV SERVER_TCPTIMEOUT 30
ENV SERVER_RETRYONERROR 3
ENV SERVER_DEADBACKENDON500 false
ENV SERVER_HTTPKEEPALIVE false
ENV SERVER_LRUCACHE_SIZE 5
ENV SERVER_LRUCACHE_TTL 5
ENV SERVER_PORT 443
ENV SERVER_ADDRESS '["0.0.0.0"]'
ENV DRIVER redis:

ENV HIPACHE_HTTP_BIND '["0.0.0.0"]'
ENV HIPACHE_HTTP_PORT 80

ENV HIPACHE_HTTPS_BIND '["0.0.0.0"]'
ENV HIPACHE_HTTPS_PORT 443
ENV HIPACHE_HTTPS_CA '[]'
ENV HIPACHE_HTTPS_SECURE_PROTOCOL SSLv23_method
ENV HIPACHE_HTTPS_SECURE_OPTIONS 50331648
ENV HIPACHE_HTTPS_SECURE_KEY /opt/ssl/ssl.key
ENV HIPACHE_HTTPS_SECURE_CERT /opt/ssl/ssl.crt
ENV HIPACHE_HTTPS_PASSPHRASE null
ENV HIPACHE_HTTPS_CIPHERS 'DH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+a RSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4'
ENV HIPACHE_HTTPS_HONOR_CIPHER_ORDER true

ENV HIPACHE_USER www-data
ENV HIPACHE_GROUP www-data

ADD ./scripts /opt/scripts
RUN chmod +x /opt/scripts/*.sh
ADD ./ssl /opt/ssl

ENV HIPACHE_SSL_KEY_DATA ""
ENV HIPACHE_SSL_CERT_DATA ""

EXPOSE 10080
EXPOSE 10443

CMD ["/opt/scripts/run.sh"]